# Generated by Django 5.1.3 on 2024-11-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='foodItems',
            new_name='fooditem',
        ),
    ]
